/**
 * @file      control_data.c
 *
 * @brief     Control driver
 *
 * @date      2023-02-21
 *
 */

/** \addtogroup module
 *  @{
 */

/******************************************************************************
 * INCLUDES
 ******************************************************************************/

#include "control_drv.h"
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <general_types.h>
#include <general_macros.h>
#include "encoder_drv.h"
#include "buttons_drv.h"
#include "stm32f10x.h"

/******************************************************************************
 * DEFINES
 ******************************************************************************/


/******************************************************************************
 * PRIVATE TYPES
 ******************************************************************************/


/******************************************************************************
 * PRIVATE DATA
 ******************************************************************************/

control_cfg_t control_cfg_default = {
	   .sw7_fsm_table = {
       {CONTROL_ENCODER_SW7_VAR0_CC, CONTROL_ENCODER_SW7_VAR0_DATA},
       {CONTROL_ENCODER_SW7_VAR1_CC, CONTROL_ENCODER_SW7_VAR1_DATA},
       {CONTROL_ENCODER_SW7_VAR2_CC, CONTROL_ENCODER_SW7_VAR2_DATA},
       {CONTROL_ENCODER_SW7_VAR3_CC, CONTROL_ENCODER_SW7_VAR3_DATA},
       {CONTROL_ENCODER_SW7_VAR4_CC, CONTROL_ENCODER_SW7_VAR4_DATA},
       {CONTROL_ENCODER_SW7_VAR5_CC, CONTROL_ENCODER_SW7_VAR5_DATA},
       {CONTROL_ENCODER_SW7_VAR6_CC, CONTROL_ENCODER_SW7_VAR6_DATA},
       {CONTROL_ENCODER_SW7_VAR7_CC, CONTROL_ENCODER_SW7_VAR7_DATA},
       {CONTROL_ENCODER_SW7_VAR8_CC, CONTROL_ENCODER_SW7_VAR8_DATA},
       {CONTROL_ENCODER_SW7_VAR9_CC, CONTROL_ENCODER_SW7_VAR9_DATA},
       {CONTROL_ENCODER_SW7_VAR10_CC, CONTROL_ENCODER_SW7_VAR10_DATA},
       {CONTROL_ENCODER_SW7_VAR11_CC, CONTROL_ENCODER_SW7_VAR11_DATA},
       {CONTROL_ENCODER_SW7_VAR12_CC, CONTROL_ENCODER_SW7_VAR12_DATA},
       {CONTROL_ENCODER_SW7_VAR13_CC, CONTROL_ENCODER_SW7_VAR13_DATA},
       {CONTROL_ENCODER_SW7_VAR14_CC, CONTROL_ENCODER_SW7_VAR14_DATA},
       {CONTROL_ENCODER_SW7_VAR15_CC, CONTROL_ENCODER_SW7_VAR15_DATA},
       {CONTROL_ENCODER_SW7_VAR16_CC, CONTROL_ENCODER_SW7_VAR16_DATA},
       {CONTROL_ENCODER_SW7_VAR17_CC, CONTROL_ENCODER_SW7_VAR17_DATA},
       {CONTROL_ENCODER_SW7_VAR18_CC, CONTROL_ENCODER_SW7_VAR18_DATA},
       {CONTROL_ENCODER_SW7_VAR19_CC, CONTROL_ENCODER_SW7_VAR19_DATA},
       {CONTROL_ENCODER_SW7_VAR20_CC, CONTROL_ENCODER_SW7_VAR20_DATA},
       {CONTROL_ENCODER_SW7_VAR21_CC, CONTROL_ENCODER_SW7_VAR21_DATA},
       {CONTROL_ENCODER_SW7_VAR22_CC, CONTROL_ENCODER_SW7_VAR22_DATA},
       {CONTROL_ENCODER_SW7_VAR23_CC, CONTROL_ENCODER_SW7_VAR23_DATA},
       {CONTROL_ENCODER_SW7_VAR24_CC, CONTROL_ENCODER_SW7_VAR24_DATA},
       {CONTROL_ENCODER_SW7_VAR25_CC, CONTROL_ENCODER_SW7_VAR25_DATA},
       {CONTROL_ENCODER_SW7_VAR26_CC, CONTROL_ENCODER_SW7_VAR26_DATA},
       {CONTROL_ENCODER_SW7_VAR27_CC, CONTROL_ENCODER_SW7_VAR27_DATA},
       {CONTROL_ENCODER_SW7_VAR28_CC, CONTROL_ENCODER_SW7_VAR28_DATA},
       {CONTROL_ENCODER_SW7_VAR29_CC, CONTROL_ENCODER_SW7_VAR29_DATA},
       {CONTROL_ENCODER_SW7_VAR30_CC, CONTROL_ENCODER_SW7_VAR30_DATA},
       {CONTROL_ENCODER_SW7_VAR31_CC, CONTROL_ENCODER_SW7_VAR31_DATA},
       {CONTROL_ENCODER_SW7_VAR32_CC, CONTROL_ENCODER_SW7_VAR32_DATA},
       {CONTROL_ENCODER_SW7_VAR33_CC, CONTROL_ENCODER_SW7_VAR33_DATA},
       {CONTROL_ENCODER_SW7_VAR34_CC, CONTROL_ENCODER_SW7_VAR34_DATA},
       {CONTROL_ENCODER_SW7_VAR35_CC, CONTROL_ENCODER_SW7_VAR35_DATA},
       {CONTROL_ENCODER_SW7_VAR36_CC, CONTROL_ENCODER_SW7_VAR36_DATA},
       {CONTROL_ENCODER_SW7_VAR37_CC, CONTROL_ENCODER_SW7_VAR37_DATA},
       {CONTROL_ENCODER_SW7_VAR38_CC, CONTROL_ENCODER_SW7_VAR38_DATA},
       {CONTROL_ENCODER_SW7_VAR39_CC, CONTROL_ENCODER_SW7_VAR39_DATA},
       {CONTROL_ENCODER_SW7_VAR40_CC, CONTROL_ENCODER_SW7_VAR40_DATA},
       {CONTROL_ENCODER_SW7_VAR41_CC, CONTROL_ENCODER_SW7_VAR41_DATA},
       {CONTROL_ENCODER_SW7_VAR42_CC, CONTROL_ENCODER_SW7_VAR42_DATA},
       {CONTROL_ENCODER_SW7_VAR43_CC, CONTROL_ENCODER_SW7_VAR43_DATA},
       {CONTROL_ENCODER_SW7_VAR44_CC, CONTROL_ENCODER_SW7_VAR44_DATA},
       {CONTROL_ENCODER_SW7_VAR45_CC, CONTROL_ENCODER_SW7_VAR45_DATA},
       {CONTROL_ENCODER_SW7_VAR46_CC, CONTROL_ENCODER_SW7_VAR46_DATA},
       {CONTROL_ENCODER_SW7_VAR47_CC, CONTROL_ENCODER_SW7_VAR47_DATA}
       },
	   .sw9_fsm_table = {
       {CONTROL_ENCODER_SW9_VAR0_CC, CONTROL_ENCODER_SW9_VAR0_DATA},
       {CONTROL_ENCODER_SW9_VAR1_CC, CONTROL_ENCODER_SW9_VAR1_DATA},
       {CONTROL_ENCODER_SW9_VAR2_CC, CONTROL_ENCODER_SW9_VAR2_DATA},
       {CONTROL_ENCODER_SW9_VAR3_CC, CONTROL_ENCODER_SW9_VAR3_DATA},
       {CONTROL_ENCODER_SW9_VAR4_CC, CONTROL_ENCODER_SW9_VAR4_DATA},
       {CONTROL_ENCODER_SW9_VAR5_CC, CONTROL_ENCODER_SW9_VAR5_DATA},
       {CONTROL_ENCODER_SW9_VAR6_CC, CONTROL_ENCODER_SW9_VAR6_DATA},
       {CONTROL_ENCODER_SW9_VAR7_CC, CONTROL_ENCODER_SW9_VAR7_DATA},
       {CONTROL_ENCODER_SW9_VAR8_CC, CONTROL_ENCODER_SW9_VAR8_DATA},
       {CONTROL_ENCODER_SW9_VAR9_CC, CONTROL_ENCODER_SW9_VAR9_DATA},
       {CONTROL_ENCODER_SW9_VAR10_CC, CONTROL_ENCODER_SW9_VAR10_DATA},
       {CONTROL_ENCODER_SW9_VAR11_CC, CONTROL_ENCODER_SW9_VAR11_DATA},
       {CONTROL_ENCODER_SW9_VAR12_CC, CONTROL_ENCODER_SW9_VAR12_DATA},
       {CONTROL_ENCODER_SW9_VAR13_CC, CONTROL_ENCODER_SW9_VAR13_DATA},
       {CONTROL_ENCODER_SW9_VAR14_CC, CONTROL_ENCODER_SW9_VAR14_DATA},
       {CONTROL_ENCODER_SW9_VAR15_CC, CONTROL_ENCODER_SW9_VAR15_DATA},
       {CONTROL_ENCODER_SW9_VAR16_CC, CONTROL_ENCODER_SW9_VAR16_DATA},
       {CONTROL_ENCODER_SW9_VAR17_CC, CONTROL_ENCODER_SW9_VAR17_DATA},
       {CONTROL_ENCODER_SW9_VAR18_CC, CONTROL_ENCODER_SW9_VAR18_DATA},
       {CONTROL_ENCODER_SW9_VAR19_CC, CONTROL_ENCODER_SW9_VAR19_DATA},
       {CONTROL_ENCODER_SW9_VAR20_CC, CONTROL_ENCODER_SW9_VAR20_DATA},
       {CONTROL_ENCODER_SW9_VAR21_CC, CONTROL_ENCODER_SW9_VAR21_DATA},
       {CONTROL_ENCODER_SW9_VAR22_CC, CONTROL_ENCODER_SW9_VAR22_DATA},
       {CONTROL_ENCODER_SW9_VAR23_CC, CONTROL_ENCODER_SW9_VAR23_DATA},
       {CONTROL_ENCODER_SW9_VAR24_CC, CONTROL_ENCODER_SW9_VAR24_DATA},
       {CONTROL_ENCODER_SW9_VAR25_CC, CONTROL_ENCODER_SW9_VAR25_DATA},
       {CONTROL_ENCODER_SW9_VAR26_CC, CONTROL_ENCODER_SW9_VAR26_DATA},
       {CONTROL_ENCODER_SW9_VAR27_CC, CONTROL_ENCODER_SW9_VAR27_DATA},
       {CONTROL_ENCODER_SW9_VAR28_CC, CONTROL_ENCODER_SW9_VAR28_DATA},
       {CONTROL_ENCODER_SW9_VAR29_CC, CONTROL_ENCODER_SW9_VAR29_DATA},
       {CONTROL_ENCODER_SW9_VAR30_CC, CONTROL_ENCODER_SW9_VAR30_DATA},
       {CONTROL_ENCODER_SW9_VAR31_CC, CONTROL_ENCODER_SW9_VAR31_DATA},
       {CONTROL_ENCODER_SW9_VAR32_CC, CONTROL_ENCODER_SW9_VAR32_DATA},
       {CONTROL_ENCODER_SW9_VAR33_CC, CONTROL_ENCODER_SW9_VAR33_DATA},
       {CONTROL_ENCODER_SW9_VAR34_CC, CONTROL_ENCODER_SW9_VAR34_DATA},
       {CONTROL_ENCODER_SW9_VAR35_CC, CONTROL_ENCODER_SW9_VAR35_DATA},
       {CONTROL_ENCODER_SW9_VAR36_CC, CONTROL_ENCODER_SW9_VAR36_DATA},
       {CONTROL_ENCODER_SW9_VAR37_CC, CONTROL_ENCODER_SW9_VAR37_DATA},
       {CONTROL_ENCODER_SW9_VAR38_CC, CONTROL_ENCODER_SW9_VAR38_DATA},
       {CONTROL_ENCODER_SW9_VAR39_CC, CONTROL_ENCODER_SW9_VAR39_DATA},
       {CONTROL_ENCODER_SW9_VAR40_CC, CONTROL_ENCODER_SW9_VAR40_DATA},
       {CONTROL_ENCODER_SW9_VAR41_CC, CONTROL_ENCODER_SW9_VAR41_DATA},
       {CONTROL_ENCODER_SW9_VAR42_CC, CONTROL_ENCODER_SW9_VAR42_DATA},
       {CONTROL_ENCODER_SW9_VAR43_CC, CONTROL_ENCODER_SW9_VAR43_DATA},
       {CONTROL_ENCODER_SW9_VAR44_CC, CONTROL_ENCODER_SW9_VAR44_DATA},
       {CONTROL_ENCODER_SW9_VAR45_CC, CONTROL_ENCODER_SW9_VAR45_DATA},
       {CONTROL_ENCODER_SW9_VAR46_CC, CONTROL_ENCODER_SW9_VAR46_DATA},
       {CONTROL_ENCODER_SW9_VAR47_CC, CONTROL_ENCODER_SW9_VAR47_DATA}},
	   .sw10_fsm_table = {
       {CONTROL_ENCODER_SW10_VAR0_CC, CONTROL_ENCODER_SW10_VAR0_DATA},
       {CONTROL_ENCODER_SW10_VAR1_CC, CONTROL_ENCODER_SW10_VAR1_DATA},
       {CONTROL_ENCODER_SW10_VAR2_CC, CONTROL_ENCODER_SW10_VAR2_DATA},
       {CONTROL_ENCODER_SW10_VAR3_CC, CONTROL_ENCODER_SW10_VAR3_DATA},
       {CONTROL_ENCODER_SW10_VAR4_CC, CONTROL_ENCODER_SW10_VAR4_DATA},
       {CONTROL_ENCODER_SW10_VAR5_CC, CONTROL_ENCODER_SW10_VAR5_DATA},
       {CONTROL_ENCODER_SW10_VAR6_CC, CONTROL_ENCODER_SW10_VAR6_DATA},
       {CONTROL_ENCODER_SW10_VAR7_CC, CONTROL_ENCODER_SW10_VAR7_DATA},
       {CONTROL_ENCODER_SW10_VAR8_CC, CONTROL_ENCODER_SW10_VAR8_DATA},
       {CONTROL_ENCODER_SW10_VAR9_CC, CONTROL_ENCODER_SW10_VAR9_DATA},
       {CONTROL_ENCODER_SW10_VAR10_CC, CONTROL_ENCODER_SW10_VAR10_DATA},
       {CONTROL_ENCODER_SW10_VAR11_CC, CONTROL_ENCODER_SW10_VAR11_DATA},
       {CONTROL_ENCODER_SW10_VAR12_CC, CONTROL_ENCODER_SW10_VAR12_DATA},
       {CONTROL_ENCODER_SW10_VAR13_CC, CONTROL_ENCODER_SW10_VAR13_DATA},
       {CONTROL_ENCODER_SW10_VAR14_CC, CONTROL_ENCODER_SW10_VAR14_DATA},
       {CONTROL_ENCODER_SW10_VAR15_CC, CONTROL_ENCODER_SW10_VAR15_DATA},
       {CONTROL_ENCODER_SW10_VAR16_CC, CONTROL_ENCODER_SW10_VAR16_DATA},
       {CONTROL_ENCODER_SW10_VAR17_CC, CONTROL_ENCODER_SW10_VAR17_DATA},
       {CONTROL_ENCODER_SW10_VAR18_CC, CONTROL_ENCODER_SW10_VAR18_DATA},
       {CONTROL_ENCODER_SW10_VAR19_CC, CONTROL_ENCODER_SW10_VAR19_DATA},
       {CONTROL_ENCODER_SW10_VAR20_CC, CONTROL_ENCODER_SW10_VAR20_DATA},
       {CONTROL_ENCODER_SW10_VAR21_CC, CONTROL_ENCODER_SW10_VAR21_DATA},
       {CONTROL_ENCODER_SW10_VAR22_CC, CONTROL_ENCODER_SW10_VAR22_DATA},
       {CONTROL_ENCODER_SW10_VAR23_CC, CONTROL_ENCODER_SW10_VAR23_DATA},
       {CONTROL_ENCODER_SW10_VAR24_CC, CONTROL_ENCODER_SW10_VAR24_DATA},
       {CONTROL_ENCODER_SW10_VAR25_CC, CONTROL_ENCODER_SW10_VAR25_DATA},
       {CONTROL_ENCODER_SW10_VAR26_CC, CONTROL_ENCODER_SW10_VAR26_DATA},
       {CONTROL_ENCODER_SW10_VAR27_CC, CONTROL_ENCODER_SW10_VAR27_DATA},
       {CONTROL_ENCODER_SW10_VAR28_CC, CONTROL_ENCODER_SW10_VAR28_DATA},
       {CONTROL_ENCODER_SW10_VAR29_CC, CONTROL_ENCODER_SW10_VAR29_DATA},
       {CONTROL_ENCODER_SW10_VAR30_CC, CONTROL_ENCODER_SW10_VAR30_DATA},
       {CONTROL_ENCODER_SW10_VAR31_CC, CONTROL_ENCODER_SW10_VAR31_DATA},
       {CONTROL_ENCODER_SW10_VAR32_CC, CONTROL_ENCODER_SW10_VAR32_DATA},
       {CONTROL_ENCODER_SW10_VAR33_CC, CONTROL_ENCODER_SW10_VAR33_DATA},
       {CONTROL_ENCODER_SW10_VAR34_CC, CONTROL_ENCODER_SW10_VAR34_DATA},
       {CONTROL_ENCODER_SW10_VAR35_CC, CONTROL_ENCODER_SW10_VAR35_DATA},
       {CONTROL_ENCODER_SW10_VAR36_CC, CONTROL_ENCODER_SW10_VAR36_DATA},
       {CONTROL_ENCODER_SW10_VAR37_CC, CONTROL_ENCODER_SW10_VAR37_DATA},
       {CONTROL_ENCODER_SW10_VAR38_CC, CONTROL_ENCODER_SW10_VAR38_DATA},
       {CONTROL_ENCODER_SW10_VAR39_CC, CONTROL_ENCODER_SW10_VAR39_DATA},
       {CONTROL_ENCODER_SW10_VAR40_CC, CONTROL_ENCODER_SW10_VAR40_DATA},
       {CONTROL_ENCODER_SW10_VAR41_CC, CONTROL_ENCODER_SW10_VAR41_DATA},
       {CONTROL_ENCODER_SW10_VAR42_CC, CONTROL_ENCODER_SW10_VAR42_DATA},
       {CONTROL_ENCODER_SW10_VAR43_CC, CONTROL_ENCODER_SW10_VAR43_DATA},
       {CONTROL_ENCODER_SW10_VAR44_CC, CONTROL_ENCODER_SW10_VAR44_DATA},
       {CONTROL_ENCODER_SW10_VAR45_CC, CONTROL_ENCODER_SW10_VAR45_DATA},
       {CONTROL_ENCODER_SW10_VAR46_CC, CONTROL_ENCODER_SW10_VAR46_DATA},
       {CONTROL_ENCODER_SW10_VAR47_CC, CONTROL_ENCODER_SW10_VAR47_DATA}},
	   .sw1_fsm_table = {
       {CONTROL_ENCODER_SW1_VAR0_CC, CONTROL_ENCODER_SW1_VAR0_DATA},
       {CONTROL_ENCODER_SW1_VAR1_CC, CONTROL_ENCODER_SW1_VAR1_DATA},
       {CONTROL_ENCODER_SW1_VAR2_CC, CONTROL_ENCODER_SW1_VAR2_DATA},
       {CONTROL_ENCODER_SW1_VAR3_CC, CONTROL_ENCODER_SW1_VAR3_DATA},
       {CONTROL_ENCODER_SW1_VAR4_CC, CONTROL_ENCODER_SW1_VAR4_DATA},
       {CONTROL_ENCODER_SW1_VAR5_CC, CONTROL_ENCODER_SW1_VAR5_DATA},
       {CONTROL_ENCODER_SW1_VAR6_CC, CONTROL_ENCODER_SW1_VAR6_DATA},
       {CONTROL_ENCODER_SW1_VAR7_CC, CONTROL_ENCODER_SW1_VAR7_DATA},
       {CONTROL_ENCODER_SW1_VAR8_CC, CONTROL_ENCODER_SW1_VAR8_DATA},
       {CONTROL_ENCODER_SW1_VAR9_CC, CONTROL_ENCODER_SW1_VAR9_DATA},
       {CONTROL_ENCODER_SW1_VAR10_CC, CONTROL_ENCODER_SW1_VAR10_DATA},
       {CONTROL_ENCODER_SW1_VAR11_CC, CONTROL_ENCODER_SW1_VAR11_DATA},
       {CONTROL_ENCODER_SW1_VAR12_CC, CONTROL_ENCODER_SW1_VAR12_DATA},
       {CONTROL_ENCODER_SW1_VAR13_CC, CONTROL_ENCODER_SW1_VAR13_DATA},
       {CONTROL_ENCODER_SW1_VAR14_CC, CONTROL_ENCODER_SW1_VAR14_DATA},
       {CONTROL_ENCODER_SW1_VAR15_CC, CONTROL_ENCODER_SW1_VAR15_DATA},
       {CONTROL_ENCODER_SW1_VAR16_CC, CONTROL_ENCODER_SW1_VAR16_DATA},
       {CONTROL_ENCODER_SW1_VAR17_CC, CONTROL_ENCODER_SW1_VAR17_DATA},
       {CONTROL_ENCODER_SW1_VAR18_CC, CONTROL_ENCODER_SW1_VAR18_DATA},
       {CONTROL_ENCODER_SW1_VAR19_CC, CONTROL_ENCODER_SW1_VAR19_DATA},
       {CONTROL_ENCODER_SW1_VAR20_CC, CONTROL_ENCODER_SW1_VAR20_DATA},
       {CONTROL_ENCODER_SW1_VAR21_CC, CONTROL_ENCODER_SW1_VAR21_DATA},
       {CONTROL_ENCODER_SW1_VAR22_CC, CONTROL_ENCODER_SW1_VAR22_DATA},
       {CONTROL_ENCODER_SW1_VAR23_CC, CONTROL_ENCODER_SW1_VAR23_DATA}
        },
	   .sw2_fsm_table = {
       {CONTROL_ENCODER_SW2_VAR0_CC, CONTROL_ENCODER_SW2_VAR0_DATA},
       {CONTROL_ENCODER_SW2_VAR1_CC, CONTROL_ENCODER_SW2_VAR1_DATA},
       {CONTROL_ENCODER_SW2_VAR2_CC, CONTROL_ENCODER_SW2_VAR2_DATA},
       {CONTROL_ENCODER_SW2_VAR3_CC, CONTROL_ENCODER_SW2_VAR3_DATA},
       {CONTROL_ENCODER_SW2_VAR4_CC, CONTROL_ENCODER_SW2_VAR4_DATA},
       {CONTROL_ENCODER_SW2_VAR5_CC, CONTROL_ENCODER_SW2_VAR5_DATA},
       {CONTROL_ENCODER_SW2_VAR6_CC, CONTROL_ENCODER_SW2_VAR6_DATA},
       {CONTROL_ENCODER_SW2_VAR7_CC, CONTROL_ENCODER_SW2_VAR7_DATA},
       {CONTROL_ENCODER_SW2_VAR8_CC, CONTROL_ENCODER_SW2_VAR8_DATA},
       {CONTROL_ENCODER_SW2_VAR9_CC, CONTROL_ENCODER_SW2_VAR9_DATA},
       {CONTROL_ENCODER_SW2_VAR10_CC, CONTROL_ENCODER_SW2_VAR10_DATA},
       {CONTROL_ENCODER_SW2_VAR11_CC, CONTROL_ENCODER_SW2_VAR11_DATA},
       {CONTROL_ENCODER_SW2_VAR12_CC, CONTROL_ENCODER_SW2_VAR12_DATA},
       {CONTROL_ENCODER_SW2_VAR13_CC, CONTROL_ENCODER_SW2_VAR13_DATA},
       {CONTROL_ENCODER_SW2_VAR14_CC, CONTROL_ENCODER_SW2_VAR14_DATA},
       {CONTROL_ENCODER_SW2_VAR15_CC, CONTROL_ENCODER_SW2_VAR15_DATA},
       {CONTROL_ENCODER_SW2_VAR16_CC, CONTROL_ENCODER_SW2_VAR16_DATA},
       {CONTROL_ENCODER_SW2_VAR17_CC, CONTROL_ENCODER_SW2_VAR17_DATA},
       {CONTROL_ENCODER_SW2_VAR18_CC, CONTROL_ENCODER_SW2_VAR18_DATA},
       {CONTROL_ENCODER_SW2_VAR19_CC, CONTROL_ENCODER_SW2_VAR19_DATA},
       {CONTROL_ENCODER_SW2_VAR20_CC, CONTROL_ENCODER_SW2_VAR20_DATA},
       {CONTROL_ENCODER_SW2_VAR21_CC, CONTROL_ENCODER_SW2_VAR21_DATA},
       {CONTROL_ENCODER_SW2_VAR22_CC, CONTROL_ENCODER_SW2_VAR22_DATA},
       {CONTROL_ENCODER_SW2_VAR23_CC, CONTROL_ENCODER_SW2_VAR23_DATA}
       },
	   .sw3_fsm_table = {
       {CONTROL_ENCODER_SW3_VAR0_CC, CONTROL_ENCODER_SW3_VAR0_DATA},
       {CONTROL_ENCODER_SW3_VAR1_CC, CONTROL_ENCODER_SW3_VAR1_DATA},
       {CONTROL_ENCODER_SW3_VAR2_CC, CONTROL_ENCODER_SW3_VAR2_DATA},
       {CONTROL_ENCODER_SW3_VAR3_CC, CONTROL_ENCODER_SW3_VAR3_DATA},
       {CONTROL_ENCODER_SW3_VAR4_CC, CONTROL_ENCODER_SW3_VAR4_DATA},
       {CONTROL_ENCODER_SW3_VAR5_CC, CONTROL_ENCODER_SW3_VAR5_DATA},
       {CONTROL_ENCODER_SW3_VAR6_CC, CONTROL_ENCODER_SW3_VAR6_DATA},
       {CONTROL_ENCODER_SW3_VAR7_CC, CONTROL_ENCODER_SW3_VAR7_DATA},
       {CONTROL_ENCODER_SW3_VAR8_CC, CONTROL_ENCODER_SW3_VAR8_DATA},
       {CONTROL_ENCODER_SW3_VAR9_CC, CONTROL_ENCODER_SW3_VAR9_DATA},
       {CONTROL_ENCODER_SW3_VAR10_CC, CONTROL_ENCODER_SW3_VAR10_DATA},
       {CONTROL_ENCODER_SW3_VAR11_CC, CONTROL_ENCODER_SW3_VAR11_DATA},
       {CONTROL_ENCODER_SW3_VAR12_CC, CONTROL_ENCODER_SW3_VAR12_DATA},
       {CONTROL_ENCODER_SW3_VAR13_CC, CONTROL_ENCODER_SW3_VAR13_DATA},
       {CONTROL_ENCODER_SW3_VAR14_CC, CONTROL_ENCODER_SW3_VAR14_DATA},
       {CONTROL_ENCODER_SW3_VAR15_CC, CONTROL_ENCODER_SW3_VAR15_DATA},
       {CONTROL_ENCODER_SW3_VAR16_CC, CONTROL_ENCODER_SW3_VAR16_DATA},
       {CONTROL_ENCODER_SW3_VAR17_CC, CONTROL_ENCODER_SW3_VAR17_DATA},
       {CONTROL_ENCODER_SW3_VAR18_CC, CONTROL_ENCODER_SW3_VAR18_DATA},
       {CONTROL_ENCODER_SW3_VAR19_CC, CONTROL_ENCODER_SW3_VAR19_DATA},
       {CONTROL_ENCODER_SW3_VAR20_CC, CONTROL_ENCODER_SW3_VAR20_DATA},
       {CONTROL_ENCODER_SW3_VAR21_CC, CONTROL_ENCODER_SW3_VAR21_DATA},
       {CONTROL_ENCODER_SW3_VAR22_CC, CONTROL_ENCODER_SW3_VAR22_DATA},
       {CONTROL_ENCODER_SW3_VAR23_CC, CONTROL_ENCODER_SW3_VAR23_DATA}
       },
       .sw4_fsm_table = {
       {CONTROL_ENCODER_SW4_VAR0_CC, CONTROL_ENCODER_SW4_VAR0_DATA},
       {CONTROL_ENCODER_SW4_VAR1_CC, CONTROL_ENCODER_SW4_VAR1_DATA},
       {CONTROL_ENCODER_SW4_VAR2_CC, CONTROL_ENCODER_SW4_VAR2_DATA},
       {CONTROL_ENCODER_SW4_VAR3_CC, CONTROL_ENCODER_SW4_VAR3_DATA},
       {CONTROL_ENCODER_SW4_VAR4_CC, CONTROL_ENCODER_SW4_VAR4_DATA},
       {CONTROL_ENCODER_SW4_VAR5_CC, CONTROL_ENCODER_SW4_VAR5_DATA},
       {CONTROL_ENCODER_SW4_VAR6_CC, CONTROL_ENCODER_SW4_VAR6_DATA},
       {CONTROL_ENCODER_SW4_VAR7_CC, CONTROL_ENCODER_SW4_VAR7_DATA},
       {CONTROL_ENCODER_SW4_VAR8_CC, CONTROL_ENCODER_SW4_VAR8_DATA},
       {CONTROL_ENCODER_SW4_VAR9_CC, CONTROL_ENCODER_SW4_VAR9_DATA},
       {CONTROL_ENCODER_SW4_VAR10_CC, CONTROL_ENCODER_SW4_VAR10_DATA},
       {CONTROL_ENCODER_SW4_VAR11_CC, CONTROL_ENCODER_SW4_VAR11_DATA},
       {CONTROL_ENCODER_SW4_VAR12_CC, CONTROL_ENCODER_SW4_VAR12_DATA},
       {CONTROL_ENCODER_SW4_VAR13_CC, CONTROL_ENCODER_SW4_VAR13_DATA},
       {CONTROL_ENCODER_SW4_VAR14_CC, CONTROL_ENCODER_SW4_VAR14_DATA},
       {CONTROL_ENCODER_SW4_VAR15_CC, CONTROL_ENCODER_SW4_VAR15_DATA},
       {CONTROL_ENCODER_SW4_VAR16_CC, CONTROL_ENCODER_SW4_VAR16_DATA},
       {CONTROL_ENCODER_SW4_VAR17_CC, CONTROL_ENCODER_SW4_VAR17_DATA},
       {CONTROL_ENCODER_SW4_VAR18_CC, CONTROL_ENCODER_SW4_VAR18_DATA},
       {CONTROL_ENCODER_SW4_VAR19_CC, CONTROL_ENCODER_SW4_VAR19_DATA},
       {CONTROL_ENCODER_SW4_VAR20_CC, CONTROL_ENCODER_SW4_VAR20_DATA},
       {CONTROL_ENCODER_SW4_VAR21_CC, CONTROL_ENCODER_SW4_VAR21_DATA},
       {CONTROL_ENCODER_SW4_VAR22_CC, CONTROL_ENCODER_SW4_VAR22_DATA},
       {CONTROL_ENCODER_SW4_VAR23_CC, CONTROL_ENCODER_SW4_VAR23_DATA}
       },
       .sw5_fsm_table = {
       {CONTROL_ENCODER_SW5_VAR0_CC, CONTROL_ENCODER_SW5_VAR0_DATA},
       {CONTROL_ENCODER_SW5_VAR1_CC, CONTROL_ENCODER_SW5_VAR1_DATA},
       {CONTROL_ENCODER_SW5_VAR2_CC, CONTROL_ENCODER_SW5_VAR2_DATA},
       {CONTROL_ENCODER_SW5_VAR3_CC, CONTROL_ENCODER_SW5_VAR3_DATA},
       {CONTROL_ENCODER_SW5_VAR4_CC, CONTROL_ENCODER_SW5_VAR4_DATA},
       {CONTROL_ENCODER_SW5_VAR5_CC, CONTROL_ENCODER_SW5_VAR5_DATA},
       {CONTROL_ENCODER_SW5_VAR6_CC, CONTROL_ENCODER_SW5_VAR6_DATA},
       {CONTROL_ENCODER_SW5_VAR7_CC, CONTROL_ENCODER_SW5_VAR7_DATA},
       {CONTROL_ENCODER_SW5_VAR8_CC, CONTROL_ENCODER_SW5_VAR8_DATA},
       {CONTROL_ENCODER_SW5_VAR9_CC, CONTROL_ENCODER_SW5_VAR9_DATA},
       {CONTROL_ENCODER_SW5_VAR10_CC, CONTROL_ENCODER_SW5_VAR10_DATA},
       {CONTROL_ENCODER_SW5_VAR11_CC, CONTROL_ENCODER_SW5_VAR11_DATA},
       {CONTROL_ENCODER_SW5_VAR12_CC, CONTROL_ENCODER_SW5_VAR12_DATA},
       {CONTROL_ENCODER_SW5_VAR13_CC, CONTROL_ENCODER_SW5_VAR13_DATA},
       {CONTROL_ENCODER_SW5_VAR14_CC, CONTROL_ENCODER_SW5_VAR14_DATA},
       {CONTROL_ENCODER_SW5_VAR15_CC, CONTROL_ENCODER_SW5_VAR15_DATA},
       {CONTROL_ENCODER_SW5_VAR16_CC, CONTROL_ENCODER_SW5_VAR16_DATA},
       {CONTROL_ENCODER_SW5_VAR17_CC, CONTROL_ENCODER_SW5_VAR17_DATA},
       {CONTROL_ENCODER_SW5_VAR18_CC, CONTROL_ENCODER_SW5_VAR18_DATA},
       {CONTROL_ENCODER_SW5_VAR19_CC, CONTROL_ENCODER_SW5_VAR19_DATA},
       {CONTROL_ENCODER_SW5_VAR20_CC, CONTROL_ENCODER_SW5_VAR20_DATA},
       {CONTROL_ENCODER_SW5_VAR21_CC, CONTROL_ENCODER_SW5_VAR21_DATA},
       {CONTROL_ENCODER_SW5_VAR22_CC, CONTROL_ENCODER_SW5_VAR22_DATA},
       {CONTROL_ENCODER_SW5_VAR23_CC, CONTROL_ENCODER_SW5_VAR23_DATA}
       },
       .sw6_fsm_table = {
       {CONTROL_ENCODER_SW6_VAR0_CC, CONTROL_ENCODER_SW6_VAR0_DATA},
       {CONTROL_ENCODER_SW6_VAR1_CC, CONTROL_ENCODER_SW6_VAR1_DATA},
       {CONTROL_ENCODER_SW6_VAR2_CC, CONTROL_ENCODER_SW6_VAR2_DATA},
       {CONTROL_ENCODER_SW6_VAR3_CC, CONTROL_ENCODER_SW6_VAR3_DATA},
       {CONTROL_ENCODER_SW6_VAR4_CC, CONTROL_ENCODER_SW6_VAR4_DATA},
       {CONTROL_ENCODER_SW6_VAR5_CC, CONTROL_ENCODER_SW6_VAR5_DATA},
       {CONTROL_ENCODER_SW6_VAR6_CC, CONTROL_ENCODER_SW6_VAR6_DATA},
       {CONTROL_ENCODER_SW6_VAR7_CC, CONTROL_ENCODER_SW6_VAR7_DATA},
       {CONTROL_ENCODER_SW6_VAR8_CC, CONTROL_ENCODER_SW6_VAR8_DATA},
       {CONTROL_ENCODER_SW6_VAR9_CC, CONTROL_ENCODER_SW6_VAR9_DATA},
       {CONTROL_ENCODER_SW6_VAR10_CC, CONTROL_ENCODER_SW6_VAR10_DATA},
       {CONTROL_ENCODER_SW6_VAR11_CC, CONTROL_ENCODER_SW6_VAR11_DATA},
       {CONTROL_ENCODER_SW6_VAR12_CC, CONTROL_ENCODER_SW6_VAR12_DATA},
       {CONTROL_ENCODER_SW6_VAR13_CC, CONTROL_ENCODER_SW6_VAR13_DATA},
       {CONTROL_ENCODER_SW6_VAR14_CC, CONTROL_ENCODER_SW6_VAR14_DATA},
       {CONTROL_ENCODER_SW6_VAR15_CC, CONTROL_ENCODER_SW6_VAR15_DATA},
       {CONTROL_ENCODER_SW6_VAR16_CC, CONTROL_ENCODER_SW6_VAR16_DATA},
       {CONTROL_ENCODER_SW6_VAR17_CC, CONTROL_ENCODER_SW6_VAR17_DATA},
       {CONTROL_ENCODER_SW6_VAR18_CC, CONTROL_ENCODER_SW6_VAR18_DATA},
       {CONTROL_ENCODER_SW6_VAR19_CC, CONTROL_ENCODER_SW6_VAR19_DATA},
       {CONTROL_ENCODER_SW6_VAR20_CC, CONTROL_ENCODER_SW6_VAR20_DATA},
       {CONTROL_ENCODER_SW6_VAR21_CC, CONTROL_ENCODER_SW6_VAR21_DATA},
       {CONTROL_ENCODER_SW6_VAR22_CC, CONTROL_ENCODER_SW6_VAR22_DATA},
       {CONTROL_ENCODER_SW6_VAR23_CC, CONTROL_ENCODER_SW6_VAR23_DATA}
       },
       .sw7_1_fsm_table = {
       {CONTROL_ENCODER_SW7_1_VAR0_CC, CONTROL_ENCODER_SW7_1_VAR0_DATA},
       {CONTROL_ENCODER_SW7_1_VAR1_CC, CONTROL_ENCODER_SW7_1_VAR1_DATA},
       {CONTROL_ENCODER_SW7_1_VAR2_CC, CONTROL_ENCODER_SW7_1_VAR2_DATA},
       {CONTROL_ENCODER_SW7_1_VAR3_CC, CONTROL_ENCODER_SW7_1_VAR3_DATA},
       {CONTROL_ENCODER_SW7_1_VAR4_CC, CONTROL_ENCODER_SW7_1_VAR4_DATA},
       {CONTROL_ENCODER_SW7_1_VAR5_CC, CONTROL_ENCODER_SW7_1_VAR5_DATA},
       {CONTROL_ENCODER_SW7_1_VAR6_CC, CONTROL_ENCODER_SW7_1_VAR6_DATA},
       {CONTROL_ENCODER_SW7_1_VAR7_CC, CONTROL_ENCODER_SW7_1_VAR7_DATA},
       {CONTROL_ENCODER_SW7_1_VAR8_CC, CONTROL_ENCODER_SW7_1_VAR8_DATA},
       {CONTROL_ENCODER_SW7_1_VAR9_CC, CONTROL_ENCODER_SW7_1_VAR9_DATA},
       {CONTROL_ENCODER_SW7_1_VAR10_CC, CONTROL_ENCODER_SW7_1_VAR10_DATA},
       {CONTROL_ENCODER_SW7_1_VAR11_CC, CONTROL_ENCODER_SW7_1_VAR11_DATA},
       {CONTROL_ENCODER_SW7_1_VAR12_CC, CONTROL_ENCODER_SW7_1_VAR12_DATA},
       {CONTROL_ENCODER_SW7_1_VAR13_CC, CONTROL_ENCODER_SW7_1_VAR13_DATA},
       {CONTROL_ENCODER_SW7_1_VAR14_CC, CONTROL_ENCODER_SW7_1_VAR14_DATA},
       {CONTROL_ENCODER_SW7_1_VAR15_CC, CONTROL_ENCODER_SW7_1_VAR15_DATA},
       {CONTROL_ENCODER_SW7_1_VAR16_CC, CONTROL_ENCODER_SW7_1_VAR16_DATA},
       {CONTROL_ENCODER_SW7_1_VAR17_CC, CONTROL_ENCODER_SW7_1_VAR17_DATA},
       {CONTROL_ENCODER_SW7_1_VAR18_CC, CONTROL_ENCODER_SW7_1_VAR18_DATA},
       {CONTROL_ENCODER_SW7_1_VAR19_CC, CONTROL_ENCODER_SW7_1_VAR19_DATA},
       {CONTROL_ENCODER_SW7_1_VAR20_CC, CONTROL_ENCODER_SW7_1_VAR20_DATA},
       {CONTROL_ENCODER_SW7_1_VAR21_CC, CONTROL_ENCODER_SW7_1_VAR21_DATA},
       {CONTROL_ENCODER_SW7_1_VAR22_CC, CONTROL_ENCODER_SW7_1_VAR22_DATA},
       {CONTROL_ENCODER_SW7_1_VAR23_CC, CONTROL_ENCODER_SW7_1_VAR23_DATA}
       },
	   .crc32 = 0x00};

/******************************************************************************
 * PUBLIC DATA
 ******************************************************************************/

// None.



/******************************************************************************
 * EXTERNAL DATA
 ******************************************************************************/

// None.



/******************************************************************************
 * EXTERNAL FUNCTION PROTOTYPES
 ******************************************************************************/

// None.



/******************************************************************************
 * PRIVATE FUNCTION PROTOTYPES
 ******************************************************************************/

// None.



/******************************************************************************
 * PRIVATE FUNCTIONS
 ******************************************************************************/

// None.



/******************************************************************************
 * PUBLIC FUNCTIONS
 ******************************************************************************/

// None.



/******************************************************************************
 * END OF SOURCE'S CODE
 ******************************************************************************/
/** @}*/