/**
 * @file      control_data.c
 *
 * @brief     Control driver
 *
 * @date      2023-02-21
 *
 */

/** \addtogroup module
 *  @{
 */

/******************************************************************************
 * INCLUDES
 ******************************************************************************/

#include "control_drv.h"
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <general_types.h>
#include <general_macros.h>
#include "encoder_drv.h"
#include "buttons_drv.h"
#include "stm32f10x.h"

/******************************************************************************
 * DEFINES
 ******************************************************************************/


/******************************************************************************
 * PRIVATE TYPES
 ******************************************************************************/


/******************************************************************************
 * PRIVATE DATA
 ******************************************************************************/

control_cfg_t control_cfg_default = {
	   .sw7_fsm_table = {
	   {CONTROL_ENCODER_SW7_VAR0_CC, CONTROL_ENCODER_SW7_VAR0_DATA},
	   {CONTROL_ENCODER_SW7_VAR1_CC, CONTROL_ENCODER_SW7_VAR1_DATA},
	   {CONTROL_ENCODER_SW7_VAR2_CC, CONTROL_ENCODER_SW7_VAR2_DATA},
	   {CONTROL_ENCODER_SW7_VAR3_CC, CONTROL_ENCODER_SW7_VAR3_DATA},
       {CONTROL_ENCODER_SW7_VAR4_CC, CONTROL_ENCODER_SW7_VAR4_DATA},
	   {CONTROL_ENCODER_SW7_VAR5_CC, CONTROL_ENCODER_SW7_VAR5_DATA},
	   {CONTROL_ENCODER_SW7_VAR6_CC, CONTROL_ENCODER_SW7_VAR6_DATA},
	   {CONTROL_ENCODER_SW7_VAR7_CC, CONTROL_ENCODER_SW7_VAR7_DATA},
       {CONTROL_ENCODER_SW7_VAR8_CC, CONTROL_ENCODER_SW7_VAR8_DATA},
	   {CONTROL_ENCODER_SW7_VAR9_CC, CONTROL_ENCODER_SW7_VAR9_DATA},
	   {CONTROL_ENCODER_SW7_VAR10_CC, CONTROL_ENCODER_SW7_VAR10_DATA},
	   {CONTROL_ENCODER_SW7_VAR11_CC, CONTROL_ENCODER_SW7_VAR11_DATA},
       {CONTROL_ENCODER_SW7_VAR12_CC, CONTROL_ENCODER_SW7_VAR12_DATA},
	   {CONTROL_ENCODER_SW7_VAR13_CC, CONTROL_ENCODER_SW7_VAR13_DATA},
	   {CONTROL_ENCODER_SW7_VAR14_CC, CONTROL_ENCODER_SW7_VAR14_DATA},
	   {CONTROL_ENCODER_SW7_VAR15_CC, CONTROL_ENCODER_SW7_VAR15_DATA},
       {CONTROL_ENCODER_SW7_VAR16_CC, CONTROL_ENCODER_SW7_VAR16_DATA},
	   {CONTROL_ENCODER_SW7_VAR17_CC, CONTROL_ENCODER_SW7_VAR17_DATA},
	   {CONTROL_ENCODER_SW7_VAR18_CC, CONTROL_ENCODER_SW7_VAR18_DATA},
	   {CONTROL_ENCODER_SW7_VAR19_CC, CONTROL_ENCODER_SW7_VAR19_DATA},
       {CONTROL_ENCODER_SW7_VAR20_CC, CONTROL_ENCODER_SW7_VAR20_DATA},
	   {CONTROL_ENCODER_SW7_VAR21_CC, CONTROL_ENCODER_SW7_VAR21_DATA},
	   {CONTROL_ENCODER_SW7_VAR22_CC, CONTROL_ENCODER_SW7_VAR22_DATA},
	   {CONTROL_ENCODER_SW7_VAR23_CC, CONTROL_ENCODER_SW7_VAR23_DATA}},
	   .sw9_fsm_table = {
       {CONTROL_ENCODER_SW9_VAR0_CC, CONTROL_ENCODER_SW9_VAR0_DATA},
       {CONTROL_ENCODER_SW9_VAR1_CC, CONTROL_ENCODER_SW9_VAR1_DATA},
       {CONTROL_ENCODER_SW9_VAR2_CC, CONTROL_ENCODER_SW9_VAR2_DATA},
       {CONTROL_ENCODER_SW9_VAR3_CC, CONTROL_ENCODER_SW9_VAR3_DATA},
       {CONTROL_ENCODER_SW9_VAR4_CC, CONTROL_ENCODER_SW9_VAR4_DATA},
       {CONTROL_ENCODER_SW9_VAR5_CC, CONTROL_ENCODER_SW9_VAR5_DATA},
       {CONTROL_ENCODER_SW9_VAR6_CC, CONTROL_ENCODER_SW9_VAR6_DATA},
       {CONTROL_ENCODER_SW9_VAR7_CC, CONTROL_ENCODER_SW9_VAR7_DATA},
       {CONTROL_ENCODER_SW9_VAR8_CC, CONTROL_ENCODER_SW9_VAR8_DATA},
       {CONTROL_ENCODER_SW9_VAR9_CC, CONTROL_ENCODER_SW9_VAR9_DATA},
       {CONTROL_ENCODER_SW9_VAR10_CC, CONTROL_ENCODER_SW9_VAR10_DATA},
       {CONTROL_ENCODER_SW9_VAR11_CC, CONTROL_ENCODER_SW9_VAR11_DATA}},
	   .sw10_fsm_table = {
       {CONTROL_ENCODER_SW10_VAR0_CC, CONTROL_ENCODER_SW10_VAR0_DATA},
       {CONTROL_ENCODER_SW10_VAR1_CC, CONTROL_ENCODER_SW10_VAR1_DATA},
       {CONTROL_ENCODER_SW10_VAR2_CC, CONTROL_ENCODER_SW10_VAR2_DATA},
       {CONTROL_ENCODER_SW10_VAR3_CC, CONTROL_ENCODER_SW10_VAR3_DATA},
       {CONTROL_ENCODER_SW10_VAR4_CC, CONTROL_ENCODER_SW10_VAR4_DATA},
       {CONTROL_ENCODER_SW10_VAR5_CC, CONTROL_ENCODER_SW10_VAR5_DATA},
       {CONTROL_ENCODER_SW10_VAR6_CC, CONTROL_ENCODER_SW10_VAR6_DATA},
       {CONTROL_ENCODER_SW10_VAR7_CC, CONTROL_ENCODER_SW10_VAR7_DATA},
       {CONTROL_ENCODER_SW10_VAR8_CC, CONTROL_ENCODER_SW10_VAR8_DATA},
       {CONTROL_ENCODER_SW10_VAR9_CC, CONTROL_ENCODER_SW10_VAR9_DATA},
       {CONTROL_ENCODER_SW10_VAR10_CC, CONTROL_ENCODER_SW10_VAR10_DATA},
       {CONTROL_ENCODER_SW10_VAR11_CC, CONTROL_ENCODER_SW10_VAR11_DATA}},
	   .sw12_fsm_table = {
	   {CONTROL_ENCODER_SW12_VAR0_CC, CONTROL_ENCODER_SW12_VAR0_DATA},
	   {CONTROL_ENCODER_SW12_VAR1_CC, CONTROL_ENCODER_SW12_VAR1_DATA},
	   {CONTROL_ENCODER_SW12_VAR2_CC, CONTROL_ENCODER_SW12_VAR2_DATA},
	   {CONTROL_ENCODER_SW12_VAR3_CC, CONTROL_ENCODER_SW12_VAR3_DATA},
       {CONTROL_ENCODER_SW12_VAR4_CC, CONTROL_ENCODER_SW12_VAR4_DATA},
	   {CONTROL_ENCODER_SW12_VAR5_CC, CONTROL_ENCODER_SW12_VAR5_DATA},
	   {CONTROL_ENCODER_SW12_VAR6_CC, CONTROL_ENCODER_SW12_VAR6_DATA},
	   {CONTROL_ENCODER_SW12_VAR7_CC, CONTROL_ENCODER_SW12_VAR7_DATA},
       {CONTROL_ENCODER_SW12_VAR8_CC, CONTROL_ENCODER_SW12_VAR8_DATA},
	   {CONTROL_ENCODER_SW12_VAR9_CC, CONTROL_ENCODER_SW12_VAR9_DATA},
	   {CONTROL_ENCODER_SW12_VAR10_CC, CONTROL_ENCODER_SW12_VAR10_DATA},
	   {CONTROL_ENCODER_SW12_VAR11_CC, CONTROL_ENCODER_SW12_VAR11_DATA},
       {CONTROL_ENCODER_SW12_VAR12_CC, CONTROL_ENCODER_SW12_VAR12_DATA},
	   {CONTROL_ENCODER_SW12_VAR13_CC, CONTROL_ENCODER_SW12_VAR13_DATA},
	   {CONTROL_ENCODER_SW12_VAR14_CC, CONTROL_ENCODER_SW12_VAR14_DATA},
	   {CONTROL_ENCODER_SW12_VAR15_CC, CONTROL_ENCODER_SW12_VAR15_DATA},
       {CONTROL_ENCODER_SW12_VAR16_CC, CONTROL_ENCODER_SW12_VAR16_DATA},
	   {CONTROL_ENCODER_SW12_VAR17_CC, CONTROL_ENCODER_SW12_VAR17_DATA},
	   {CONTROL_ENCODER_SW12_VAR18_CC, CONTROL_ENCODER_SW12_VAR18_DATA},
	   {CONTROL_ENCODER_SW12_VAR19_CC, CONTROL_ENCODER_SW12_VAR19_DATA},
       {CONTROL_ENCODER_SW12_VAR20_CC, CONTROL_ENCODER_SW12_VAR20_DATA},
	   {CONTROL_ENCODER_SW12_VAR21_CC, CONTROL_ENCODER_SW12_VAR21_DATA},
	   {CONTROL_ENCODER_SW12_VAR22_CC, CONTROL_ENCODER_SW12_VAR22_DATA},
	   {CONTROL_ENCODER_SW12_VAR23_CC, CONTROL_ENCODER_SW12_VAR23_DATA}},
	   .sw1_fsm_table = {
	   {CONTROL_ENCODER_SW1_VAR0_CC, CONTROL_ENCODER_SW1_VAR0_DATA},
       {CONTROL_ENCODER_SW1_VAR1_CC, CONTROL_ENCODER_SW1_VAR1_DATA},
       {CONTROL_ENCODER_SW1_VAR2_CC, CONTROL_ENCODER_SW1_VAR2_DATA},
       {CONTROL_ENCODER_SW1_VAR3_CC, CONTROL_ENCODER_SW1_VAR3_DATA},
       {CONTROL_ENCODER_SW1_VAR4_CC, CONTROL_ENCODER_SW1_VAR4_DATA},
       {CONTROL_ENCODER_SW1_VAR5_CC, CONTROL_ENCODER_SW1_VAR5_DATA}},
	   .sw2_fsm_table = {
       {CONTROL_ENCODER_SW2_VAR0_CC, CONTROL_ENCODER_SW2_VAR0_DATA},
       {CONTROL_ENCODER_SW2_VAR1_CC, CONTROL_ENCODER_SW2_VAR1_DATA},
       {CONTROL_ENCODER_SW2_VAR2_CC, CONTROL_ENCODER_SW2_VAR2_DATA},
       {CONTROL_ENCODER_SW2_VAR3_CC, CONTROL_ENCODER_SW2_VAR3_DATA},
       {CONTROL_ENCODER_SW2_VAR4_CC, CONTROL_ENCODER_SW2_VAR4_DATA},
       {CONTROL_ENCODER_SW2_VAR5_CC, CONTROL_ENCODER_SW2_VAR5_DATA}},
	   .sw3_fsm_table = {
       {CONTROL_ENCODER_SW3_VAR0_CC, CONTROL_ENCODER_SW3_VAR0_DATA},
       {CONTROL_ENCODER_SW3_VAR1_CC, CONTROL_ENCODER_SW3_VAR1_DATA},
       {CONTROL_ENCODER_SW3_VAR2_CC, CONTROL_ENCODER_SW3_VAR2_DATA},
       {CONTROL_ENCODER_SW3_VAR3_CC, CONTROL_ENCODER_SW3_VAR3_DATA},
       {CONTROL_ENCODER_SW3_VAR4_CC, CONTROL_ENCODER_SW3_VAR4_DATA},
       {CONTROL_ENCODER_SW3_VAR5_CC, CONTROL_ENCODER_SW3_VAR5_DATA}},
       .sw4_fsm_table = {
       {CONTROL_ENCODER_SW4_VAR0_CC, CONTROL_ENCODER_SW4_VAR0_DATA},
       {CONTROL_ENCODER_SW4_VAR1_CC, CONTROL_ENCODER_SW4_VAR1_DATA},
       {CONTROL_ENCODER_SW4_VAR2_CC, CONTROL_ENCODER_SW4_VAR2_DATA},
       {CONTROL_ENCODER_SW4_VAR3_CC, CONTROL_ENCODER_SW4_VAR3_DATA},
       {CONTROL_ENCODER_SW4_VAR4_CC, CONTROL_ENCODER_SW4_VAR4_DATA},
       {CONTROL_ENCODER_SW4_VAR5_CC, CONTROL_ENCODER_SW4_VAR5_DATA}},
       .sw5_fsm_table = {
       {CONTROL_ENCODER_SW5_VAR0_CC, CONTROL_ENCODER_SW5_VAR0_DATA},
       {CONTROL_ENCODER_SW5_VAR1_CC, CONTROL_ENCODER_SW5_VAR1_DATA},
       {CONTROL_ENCODER_SW5_VAR2_CC, CONTROL_ENCODER_SW5_VAR2_DATA},
       {CONTROL_ENCODER_SW5_VAR3_CC, CONTROL_ENCODER_SW5_VAR3_DATA},
       {CONTROL_ENCODER_SW5_VAR4_CC, CONTROL_ENCODER_SW5_VAR4_DATA},
       {CONTROL_ENCODER_SW5_VAR5_CC, CONTROL_ENCODER_SW5_VAR5_DATA}},
       .sw6_fsm_table = {
       {CONTROL_ENCODER_SW6_VAR0_CC, CONTROL_ENCODER_SW6_VAR0_DATA},
       {CONTROL_ENCODER_SW6_VAR1_CC, CONTROL_ENCODER_SW6_VAR1_DATA},
       {CONTROL_ENCODER_SW6_VAR2_CC, CONTROL_ENCODER_SW6_VAR2_DATA},
       {CONTROL_ENCODER_SW6_VAR3_CC, CONTROL_ENCODER_SW6_VAR3_DATA},
       {CONTROL_ENCODER_SW6_VAR4_CC, CONTROL_ENCODER_SW6_VAR4_DATA},
       {CONTROL_ENCODER_SW6_VAR5_CC, CONTROL_ENCODER_SW6_VAR5_DATA}},
	   .crc32 = 0x00};

/******************************************************************************
 * PUBLIC DATA
 ******************************************************************************/

// None.



/******************************************************************************
 * EXTERNAL DATA
 ******************************************************************************/

// None.



/******************************************************************************
 * EXTERNAL FUNCTION PROTOTYPES
 ******************************************************************************/

// None.



/******************************************************************************
 * PRIVATE FUNCTION PROTOTYPES
 ******************************************************************************/

// None.



/******************************************************************************
 * PRIVATE FUNCTIONS
 ******************************************************************************/

// None.



/******************************************************************************
 * PUBLIC FUNCTIONS
 ******************************************************************************/

// None.



/******************************************************************************
 * END OF SOURCE'S CODE
 ******************************************************************************/
/** @}*/